# Generated by Django 6.0.4 on 2026-05-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantcategory',
            name='color',
            field=models.CharField(default='#4caf50', max_length=7),
        ),
    ]
