# Generated by Django 6.0.4 on 2026-05-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0003_generalarea_location_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plants/'),
        ),
    ]
