# Generated by Django 6.0.4 on 2026-05-04 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0004_plant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='image',
        ),
        migrations.CreateModel(
            name='PlantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plants/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='garden.plant')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
