# Generated by Django 6.0.4 on 2026-05-04 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0005_remove_plant_image_plantimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.PositiveSmallIntegerField(choices=[(1, 'Early Spring'), (2, 'Mid Spring'), (3, 'Late Spring'), (4, 'Early Summer'), (5, 'Mid Summer'), (6, 'Late Summer'), (7, 'Early Autumn'), (8, 'Mid Autumn'), (9, 'Late Autumn'), (10, 'Early Winter'), (11, 'Mid Winter'), (12, 'Late Winter')])),
                ('task', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_tasks', to='garden.plant')),
            ],
            options={
                'ordering': ['period'],
            },
        ),
    ]
