# Generated by Django 6.0.4 on 2026-05-04 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0006_annualtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualTaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='garden.annualtask')),
            ],
            options={
                'unique_together': {('task', 'year')},
            },
        ),
    ]
