# Generated by Django 6.0.4 on 2026-05-05 07:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0007_annualtaskcompletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='areas/')),
                ('date', models.DateField(default=datetime.date.today)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='garden.generalarea')),
            ],
            options={
                'ordering': ['-date', '-uploaded_at'],
            },
        ),
    ]
